name: feanord_core
description: "A collection of utils, extensions, typedefs, custom widgets, and another bunch of classes I usually use in my Flutter projects."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  very_good_analysis: ^6.0.0

flutter: