name: feanord_core
description: "A collection of utils, extensions, typedefs, custom widgets, and another bunch of classes I usually use in my Flutter projects."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: